### ISSUE TITLE
Laravel 4.2?

### ISSUE THREAD

**Issue by rombat** [marcmascarell/laravel-artificer#4]
Hi,
You package seems to be very promising, any plan to make it available for Laravel 4.2?

**Comment by marcmascarell** [comment]
Hi,

Actually it is compatible with 4.2 ... But I dont know if Im gonna keep them compatible, what do you think?

Regards

**Comment by rombat** [comment]
Oh, ok sorry, I haven't tried your package yet. Since I read that the first stable package is aimed to work with Laravel 5, I assumed it wasn't compatible with Laravel 4.2
I'm working on a Laravel 4.2 project, and I'll have to make an admin interface, for managing (CRUD mostly) Eloquent models and other stuffs like that. Iwas checking if something like that already existed, and I found your package. Reading the readme, Artificer seems to be very promising, now and for future updates: the plugin ideas are great too. So that's why I asked this. 
That would be great to keep 4.2 compatibility.
